import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-401k-revenue-sharing-fee-recapture",
  "engine": "recovery",
  "title": "401(k) Revenue-Sharing & Fee Recapture",
  "shortTitle": "401(k) Revenue-Sharing and Fee Recapture",
  "tagline": "Calculate revenue sharing and required fee credits to prevent excess recordkeeping compensation and participant inequity.",
  "industry": "Retirement Plan Fee Governance",
  "buyer": "Plan sponsors, advisers, and fiduciaries",
  "uiPort": 4677,
  "apiPort": 5677,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "401(k) Revenue-Sharing & Fee Recapture converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations in one accountable workflow. Calculate revenue sharing and required fee credits to prevent excess recordkeeping compensation and participant inequity.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "401(k) Revenue-Sharing & Fee Recapture evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("recordkeeping-agreement-library","4RS01","Recordkeeping agreement library","Execute recordkeeping agreement library using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed recordkeeping agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Recordkeeping agreement library Reference","text","4RS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("investment-option-registry","4RS02","Investment option registry","Execute investment option registry using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed investment option registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Investment option registry Reference","text","4RS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("participant-balance-ingestion","4RS03","Participant balance ingestion","Execute participant balance ingestion using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed participant balance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Participant balance ingestion Reference","text","4RS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("revenue-sharing-rate-mapping","4RS04","Revenue-sharing rate mapping","Execute revenue-sharing rate mapping using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed revenue-sharing rate mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Revenue-sharing rate mapping Reference","text","4RS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("12b-1-calculation","4RS05","12b-1 calculation","Execute 12b-1 calculation using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed 12b-1 calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","12b-1 calculation Reference","text","4RS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("sub-ta-fee-calculation","4RS06","Sub-TA fee calculation","Execute sub-ta fee calculation using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed sub-ta fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Sub-TA fee calculation Reference","text","4RS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("shareholder-service-fee","4RS07","Shareholder service fee","Execute shareholder service fee using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed shareholder service fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Shareholder service fee Reference","text","4RS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("gross-to-net-expense-review","4RS08","Gross-to-net expense review","Execute gross-to-net expense review using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed gross-to-net expense review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Gross-to-net expense review Reference","text","4RS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("required-revenue-credit","4RS09","Required revenue credit","Execute required revenue credit using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed required revenue credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Required revenue credit Reference","text","4RS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("recordkeeper-statement-audit","4RS10","Recordkeeper statement audit","Execute recordkeeper statement audit using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed recordkeeper statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Recordkeeper statement audit Reference","text","4RS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("participant-allocation-method","4RS11","Participant allocation method","Execute participant allocation method using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed participant allocation method decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Participant allocation method Reference","text","4RS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("excess-fee-detection","4RS12","Excess fee detection","Execute excess fee detection using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed excess fee detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Excess fee detection Reference","text","4RS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("credit-correction-workflow","4RS13","Credit correction workflow","Execute credit correction workflow using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed credit correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Credit correction workflow Reference","text","4RS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("fiduciary-evidence-package","4RS14","Fiduciary evidence package","Execute fiduciary evidence package using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed fiduciary evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Fiduciary evidence package Reference","text","4RS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]}),
feature("plan-option-analytics","4RS15","Plan option analytics","Execute plan option analytics using recordkeeping agreements, investment options, participant balances, revenue-sharing rates, sub-TA fees, expense ratios, fee credits, plan expenses, and allocations.","Produce a governed plan option analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recordkeeper / Investment Option","text","Recordkeeper / Investment Option · Standard Case"],["caseReference","Plan option analytics Reference","text","4RS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",975000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1179750],["domainDriver","Revenue Source","select","12b-1",["12b-1","Sub-transfer agency","Shareholder service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Recordkeeping agreement library case","Investment option registry case","Participant balance ingestion case","Revenue-sharing rate mapping case","12b-1 calculation case"]})
]);
